### ISSUE TITLE
atb.cc error OSX yosemite

### ISSUE THREAD

**Issue by themagicianprospero** [mikeseven/node-glfw#16]
Im not completely positive what I am having is a build issue with node-glfw .
It seems everything else is in proper order . 
The examples from anttweakbar , glew, and glfw all compile and run .

This is the output from node-gyp rebuild 

Any help or advice on things to check would be incredibly helpful I do not particularly understand this output . 

If there is any additional information I can supply that would make it easier diagnose my problem don't hesitate to ask .

Thank you for you work . 

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.24 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/jamesandino/Desktop/Home/Platform/CORE/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jamesandino/Desktop/node-glfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jamesandino/Desktop/Home/Platform/CORE/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jamesandino/.node-gyp/0.10.24/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jamesandino/.node-gyp/0.10.24',
gyp info spawn args   '-Dmodule_root_dir=/Users/jamesandino/Desktop/node-glfw',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/glfw/src/atb.o
../src/atb.cc:17:23: error: 'FunctionTemplate' does not refer to a value
  NanAssignPersistent(FunctionTemplate, constructor_template, ctor);
                      ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:2252:16: note: 
      declared here
class V8EXPORT FunctionTemplate : public Template {
               ^
../src/atb.cc:19:22: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  ctor->SetClassName(NanSymbol("AntTweakBar"));
                     ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:34:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(CHAR);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:35:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(INT8);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:36:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(UINT8);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:37:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(INT16);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:38:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(UINT16);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:39:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(INT32);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:40:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(UINT32);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:41:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(FLOAT);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:42:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(DOUBLE);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:44:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(COLOR32);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:45:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(COLOR3F);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:46:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(COLOR4F);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:47:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(QUAT4F);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:48:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(QUAT4D);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:49:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(DIR3F);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:50:3: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  DEFINE_ATB_CONSTANT(DIR3D);
  ^
../src/atb.cc:11:5: note: expanded from macro 'DEFINE_ATB_CONSTANT'
    NODE_DEFINE_CONSTANT_VALUE(ctor->InstanceTemplate(), "TYPE_" #consta...
    ^
../src/atb.cc:30:17: note: expanded from macro 'NODE_DEFINE_CONSTANT_VALUE'
  (target)->Set(NanSymbol(name),                         \
                ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:54:15: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  target->Set(NanSymbol("AntTweakBar"), ctor->GetFunction());
              ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:161:23: error: 'FunctionTemplate' does not refer to a value
  NanAssignPersistent(FunctionTemplate, constructor_template, ctor);
                      ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:2252:16: note: 
      declared here
class V8EXPORT FunctionTemplate : public Template {
               ^
../src/atb.cc:163:22: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  ctor->SetClassName(NanSymbol("Bar"));
                     ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:171:15: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  target->Set(NanSymbol("Bar"), ctor->GetFunction());
              ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:203:47: error: use of undeclared identifier 'NanPersistentToLocal'
  Local<FunctionTemplate> constructorHandle = NanPersistentToLocal(const...
                                              ^
../src/atb.cc:263:39: error: use of undeclared identifier 'NanPersistentToLocal'
  Local<Function> constructorHandle = NanPersistentToLocal(cb->setter);
                                      ^
../src/atb.cc:287:23: error: use of undeclared identifier 'NanPersistentToLocal'
  Local<Function> fct=NanPersistentToLocal(cb->getter);
                      ^
../src/atb.cc:396:39: error: use of undeclared identifier 'NanPersistentToLocal'
  Local<Function> constructorHandle = NanPersistentToLocal(cb->setter);
                                      ^
../src/atb.cc:410:60: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  Local<Function> getter=Local<Function>::Cast(params->Get(JS_STR("getter")));
                                                           ^
../src/common.h:24:21: note: expanded from macro 'JS_STR'
#define JS_STR(...) NanSymbol(__VA_ARGS__)
                    ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:411:60: warning: 'NanSymbol' is deprecated
      [-Wdeprecated-declarations]
  Local<Function> setter=Local<Function>::Cast(params->Get(JS_STR("setter")));
                                                           ^
../src/common.h:24:21: note: expanded from macro 'JS_STR'
#define JS_STR(...) NanSymbol(__VA_ARGS__)
                    ^
../node_modules/nan/nan.h:825:51: note: 'NanSymbol' has been explicitly marked
      deprecated here
  NAN_DEPRECATED NAN_INLINE v8::Local<v8::String> NanSymbol(
                                                  ^
../src/atb.cc:417:23: error: 'Function' does not refer to a value
    NanInitPersistent(Function,_getter,getter);
                      ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:1770:7: note: 
      declared here
class Function : public Object {
      ^
../src/atb.cc:418:25: error: 'Function' does not refer to a value
    NanAssignPersistent(Function, callbacks->getter, _getter);
                        ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:1770:7: note: 
      declared here
class Function : public Object {
      ^
../src/atb.cc:422:23: error: 'Function' does not refer to a value
    NanInitPersistent(Function,_setter,setter);
                      ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:1770:7: note: 
      declared here
class Function : public Object {
      ^
../src/atb.cc:423:25: error: 'Function' does not refer to a value
    NanAssignPersistent(Function, callbacks->setter, _setter);
                        ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:1770:7: note: 
      declared here
class Function : public Object {
      ^
../src/atb.cc:474:23: error: 'Function' does not refer to a value
    NanInitPersistent(Function,_setter,cb);
                      ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:1770:7: note: 
      declared here
class Function : public Object {
      ^
../src/atb.cc:475:25: error: 'Function' does not refer to a value
    NanAssignPersistent(Function, callbacks->setter, _setter);
                        ^
/Users/jamesandino/.node-gyp/0.10.24/deps/v8/include/v8.h:1770:7: note: 
      declared here
class Function : public Object {
      ^
22 warnings and 12 errors generated.
make: *** [Release/obj.target/glfw/src/atb.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jamesandino/Desktop/Home/Platform/CORE/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/jamesandino/Desktop/Home/Platform/CORE/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/jamesandino/Desktop/node-glfw
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

```

**Comment by themagicianprospero** [comment]
I pulled down the latest master branch changes and its more clear how to add libraries to the bindin.gyp file and things where much simpler ; TY!
